language: php
dist: xenial

before_install: composer self-update --2

install: composer update --no-progress --prefer-dist

matrix:
  include:
    - name: PHP 7.0 Unit Tests
      php: 7.0
      install:
        - composer require php-coveralls/php-coveralls:^2.2 --dev --no-update
        - composer update --no-progress --prefer-dist
      script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
      after_success: php vendor/bin/coveralls
    - name: PHP 7.1 Unit Tests
      php: 7.1
    - name: PHP 7.2 Unit Tests
      php: 7.2
    - name: PHP 7.3 Unit Tests
      php: 7.3
    - name: PHP 7.4 Unit Tests
      php: 7.4
    - name: PHP 8.0 Unit Tests
      php: nightly
      install:
        - composer update --ignore-platform-req=php --no-progress --prefer-dist
    - name: PHP 7.3 Code on PHP 8.0 Integration Tests
      php: nightly
      install:
        - composer update --ignore-platform-req=php --no-progress --prefer-dist
      script:
        - test_old/run-php-src.sh 7.3.21
    - name: PHP 8.0 Code on PHP 7.0 Integration Tests
      php: 7.0
      script:
        - test_old/run-php-src.sh 8.0.0rc1
  fast_finish: true

script: vendor/bin/phpunit
